# Generated by Django 5.2 on 2025-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="レシピ名を入力してください",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="YouTubeのURLを入力してください", unique=True
                    ),
                ),
                (
                    "thumbnail",
                    models.URLField(help_text="サムネイル画像のURLを入力してください"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="備考を入力してください", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        help_text="カテゴリを選択してください",
                        related_name="recipes",
                        to="recipes.category",
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        help_text="使用する食材を選択してください",
                        related_name="recipes",
                        to="ingredients.ingredient",
                    ),
                ),
            ],
        ),
    ]
