# Generated by Django 5.2 on 2025-04-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="食材名を入力してください",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "reading",
                    models.CharField(
                        help_text="食材の読み方を入力してください", max_length=100
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("肉・魚・大豆・卵", "肉・魚・大豆・卵"),
                            ("野菜", "野菜"),
                            ("米・麺・パスタ", "米・麺・パスタ"),
                            ("その他", "その他"),
                        ],
                        help_text="食材の種類を選択してください",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
